name: Deploy to Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: gonzaarancibia/my-3d-portfolio-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}

      - name: Deploy to Hostinger
        run: |
          ssh u721347925@154.49.245.93 << 'EOF'
            docker pull gonzaarancibia/my-3d-portfolio-app:latest
            docker stop portfolio-container || true
            docker rm portfolio-container || true
            docker run -d --name portfolio-container -p 80:80 gonzaarancibia/my-3d-portfolio-app:latest
          EOF
